name: docs sync

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: file_changes
        uses: tj-actions/changed-files@v14.5
        id: changed-files-specific
        with:
          files: |
            docs/*
      - name: Run step only when files change.
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files listed above has changed."
        
      
